### ISSUE TITLE
Using path as a flag type results in a recursion error

### ISSUE THREAD

**Issue by esatterwhite** [esatterwhite/node-seeli#7]
This is a result of the way the options mixin works. It attempts to do a deep clone and merge of object to break inheritance references. But the path module has a circular reference on it which causes problems.
```
node-seeli/node_modules/mout/lang/deepClone.js:13
            case 'Array':
   ^

RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at kindOf (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/lang/kindOf.js:16:27)
    at deepClone (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/lang/deepClone.js:10:18)
    at Object.<anonymous> (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/lang/deepClone.js:24:29)
    at /home/esatterwhite/dev/js/node-seeli/node_modules/mout/object/forOwn.js:12:27
    at exec (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/object/forIn.js:71:19)
    at forIn (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/object/forIn.js:38:17)
    at forOwn (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/object/forOwn.js:10:9)
    at cloneObject (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/lang/deepClone.js:23:13)
    at deepClone (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/lang/deepClone.js:12:24)
    at Object.<anonymous> (/home/esatterwhite/dev/js/node-seeli/node_modules/mout/lang/deepClone.js:24:29)
```

**Comment by esatterwhite** [comment]
https://github.com/esatterwhite/node-seeli/blob/master/examples/cli.js#L40

the problem can be illustrated by change this line to be `type: require('path')` and executing the script
